---
title: "Convertibility in the universe"
subtitle: "And why should we care about this question?"
author: "Aabhas Gulati"
categories: ["Quantum Resources","Entanglement","Asymmetry"]
---

This week I will be giving a student journal club talk, and this post is written in the preparation of the talk. The question I will be discussing concerns "When can a state (of a system) be converted into another?". For this whole article, I would not be defining what a *state* is very rigourously, but intuitively we all understand that it is some way to describe a system, mathematically. 


The first situation that we will concern ourselves with is **thermodynamics**, and the simplest system we can imagine i.e an ideal gas. The state space of an ideal gas is given by $(U,V) \in \mathbb{R}_+^2$, where $U$ is the energy, and $V$ is the volume. The physical operations we can hope to perform on the gas is "heating" or "cooling" it down using some reservoir, or just changing the volume by applying some pressure or reducing pressure. We will assume that its possible to do all transformations sufficiently slowly, so that at every point the gas is at equilibrium with the external pressure, or the external reservoir. 

Is it possible for us to transform the gas from $(U,V) \rightarrow (U',V')$? 

It is easy to show that by moving in the phase diagram by using the composition of these processes accomplishes the task:
1. Change volume without adding heat to V'.
2. Add or subtract heat (at constant volume) until you get to U'.

Therefore, we can see that every state can be converted to another using all allowed "thermodynamic operations." But we can imagine that in some situations due to some constraints, we are not allowed to exchange heat with the system. We call such operations as *Adiabatic* transformations of the system. How does this restriction affect conversion of states? 

If you remember your first year thermodynamics, this is exactly a situation in which the second law of thermodynamics applies. We have a closed system, and hence the entropy of the system after the transformation must be either equal to or greater than the entropy before the transformation. 

$S(U,V) \leq S(U',V')$ if $(U,V) \rightarrow (U',V')$

Is this condition sufficient as well? What I mean is that if some pairs $(U,V)$ and $(U',V')$ satisfy the entropy condition, can we find an adiabatic transformation that connects the two. 

The answer is yes. 

We have a complete understanding of state transformations under adiabatic transformations. We represent $(U,V) \succcurlyeq (U',V')$ if the former can be converted into the latter. We note that the following conditions are true

1. $(U,V) \succcurlyeq (U,V)$. 
2. $(U,V) \succcurlyeq (U',V'), (U',V') \succcurlyeq (U'',V'') \implies (U,V) \succcurlyeq (U'',V'')$. 
3. Either $(U,V) \succcurlyeq (U',V')$ and $(U',V') \succcurlyeq (U,V)$ \implies $(U,V) = (U',V')$.

Therefore the relation that we propose completely orders the states of the ideal gas. 

That's all we will talk about thermodynamics for now. We look at something which is widely different thing in principle, but allows for similar structures. 

We consider now a state space of probability distributions on an alphabet $\Xi$, i.e $p_i \geq 0$ and $\sum_{i} p_{i \in \Xi} = 1$ and the theory of stochastic transformations. To motivate the abstract structure, we will look at the physical situation where such transformations are natural. 


These stochastic transformations can be understood as noise models for transmission of bits. In this case, the alphabet is just two element $\Xi = \{0,1\}$ and the stochastic matrix  

$$
\mathsf{P} =
\begin{pmatrix}
p(0|0) & p(1|0) \\
p(0|1) & p(1|1)
\end{pmatrix}
$$

In general any non-negative matrix with columns that sum to $1$ is called a stochastic matrix. This condition is essential to ensure that the probabilities sum to $1$. So now we have analogous objects to the thermodynamics situation. We have a description of the set of states, i.e probability distributions, and the set of transformations i.e stochastic matrices. 

So, we ask the same question (again)
Is it possible to convert any state $p$ into another state $q$ using all allowed transformations?
Consider the stochastic matrix 

$$X_{q} = \begin{bmatrix}
q, q, q \dots q
\end{bmatrix}$$

By construction, the columns sum to $1$. And multiplying it to the vector $p$ we get 
$X_{q} \cdot p  = q \sum_{x} p_{x} = q$. This achieves our desired transformation. Obviously, we are not looking here for a universal transformation for every $p$ and $q$. That cannot exist. But we have *some* transformation that does the job!

Amazing! Now, we want to look at some restricted transformations in this context. A natural restriction that you can impose on these transformations are that they preserve the maximally mixed state, which is the state 

$$\mathbb{I}_{d} = \begin{bmatrix}
\frac{1}{d} \frac{1}{d}... \frac{1}{d} 
\end{bmatrix}$$
This is the most uniform probability distribution you could expect. We will be looking at transformations that preserve this! 

$$S \cdot \mathbb{I}_d = \mathbb{I}_{d}$$Clearly we cannot hope accomplish all possible transformations now (because $\mathbb{I}_{d} \rightarrow$ anything not itself is impossible). But what are the restrictions? We need not worry, as more intelligent people asked this question long ago, and there is an elegant theory behind this. 

This is the story of majorisation. And we need to get into some definitions. 

For every vector $x$ we can define the vector $x^{\downarrow}$ which is the entries of the vector arranged in decreasing order. 

Then a vector $p$ is said to majorise another vector $q$ if $p^{\downarrow}$ and $q^{\downarrow}$ satisfy the following relation

$$ \sum_{i} p^{\downarrow}_{i} \geq  \sum_{i} q^{\downarrow}_{i}$$

For this, we usually denote it as $p \succ q$. Let us now state a few trivial propositions, 

- $\delta_{k} \succ p$ for all probability distributions. 
- $p \succ \mathbb{I}_{d}$ for all probability distributions. 

So intuitively this order tells us about how mixed a probability distribution is. There is something more interesting to note about this $\succ$ thingy. There can exist two vectors $p$ and $q$ such that none of them majorises the other! 

So why have we been discussing this (seemingly obsure) construction? Because that is exactly what characterises the transformations possible with doubly stochastic matrices. 

It is possible to transform a probability distribution from $p$ to $q$ using $\mathsf{DS}$ transformations if and only if $p \succ q$ ! 

This ends the tale of convertibility in doubly stochastic processes. So we have seen two examples, one physical, and one pretty much mathematical. This leads us to the final example in the theory of entanglement in quantum information theory. 

Should I motivate entanglement here? I think it is a big enough topic for another blog post where I explain and motivate what questions in quantum information and entanglement, that plays an essential role in the whole field, and pops up everywhere. 

States in quantum theory are given by $\ket{\psi}$ that are vectors in a Hilbert space. When we have two systems, we have states in $H_{a} \otimes H_{b}$. As you know this contains states of the form $\ket{\psi_{1}} \otimes \ket{\psi_{2}}$ but also contains all linear combinations of such states. Some of these are not of the form of a product, and these states are referred as *entangled*. 

What about processes (or transformations)? 
If you know a bit of quantum theory, you know that we can imagine doing three things, 
- Apply a unitary transformation 
- Add some more systems in the mix. 
- OR Measure. 
Given any two states $\ket{\psi}$ and $\ket{\phi}$, possibly both entangled, we can always design a process to convert from  $\ket{\psi}$ to $\ket{\phi}$ by a unitary transformation. 

$$U = \ketbra{\psi}{\phi} + \text{something orthogonal}$$
Again, we need to talk about imposing some restrictions on these processes. From a practical standpoint, we can imagine how a quantum experiment on "entangled" particles might run. 

> There are two labs. Alice, and Bob are the head of the labs, and have almost perfected running quantum experiments in their own labs. But it is impossible with the current technology to send quantum particles between labs, as they suffer from decoherence (losses to quantum properties). But they have a very good internet connection that can transmit classical information. What transformations can they achieve? 




