project:
  type: website
  output-dir: docs

website:
  title: "Aabhas Gulati"
  page-navigation: false
  search: false
  navbar:
    background: light
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - talks.qmd
      - href: blog.qmd
        text: Musings
  page-footer:
    center: "© 2026 Aabhas Gulati"

format:
  html:
    theme: default
    css: styles.css
    toc: false
    smooth-scroll: true
    html-math-method: mathjax
