---
title: ""
pagetitle: "Talks"
page-layout: custom
description: "Conference and seminar talks by Aabhas Gulati on multipartite entanglement in symmetric and bosonic quantum states."
---

::: {.page}

# Talks

## Conferences

- *Entanglement in the Dicke subspace*, Quantum Physics and Logic, Amsterdam (2026), short plenary
- *Positive maps and extendibility hierarchies from copositive matrices*, Theory of Quantum Computation, Communication and Cryptography (TQC), Sherbrooke, Canada (2026)
- *Detecting entanglement in symmetric states*, [Quantum Trajectories](https://www.icts.res.in/program/qt), ICTS Bengaluru (2025) ([slides](https://www.icts.res.in/sites/default/files/seminar%20doc%20files/ICTS_Presentation%20-%20Aabhas%20Gulati.pdf))
- *Graph based approach to detecting bound entanglement*, Young Researcher Symposium, ICMP, Strasbourg (2024)

## Seminars

- *Entanglement in the Dicke subspace*, QMATH group, University of Copenhagen (May 2026)
- *Entanglement in the Dicke subspace*, Séminaire QuantAlps, Institut Fourier, Grenoble (May 2026)
- *Entanglement in the Dicke subspace*, Séminaire LABRI, Bordeaux (May 2026)
- *Multipartite entanglement in mixtures of Dicke states*, [GIQ Seminar](https://webs.uab.cat/giq/seminar/a-complete-theory-of-multipartite-entanglement-in-diagonally-symmetric-bosonic-states/), Universitat Autònoma de Barcelona (September 2025)
- *Multipartite entanglement in diagonally symmetric states*, Quantum Information and Thermodynamics group, [TU Wien](https://quoi-theory.at/) (August 2025)

:::
